[workspace]
members = [
    ".imag-documentation",
    "bin",
    "imag-bookmark",
    "imag-counter",
    "imag-diary",
    "imag-link",
    "imag-mail",
    "imag-notes",
    "imag-ref",
    "imag-store",
    "imag-tag",
    "imag-todo",
    "imag-view",
    "libimagannotation",
    "libimagbookmark",
    "libimagcounter",
    "libimagdiary",
    "libimagentryedit",
    "libimagentryfilter",
    "libimagentrylink",
    "libimagentrylist",
    "libimagentrymarkdown",
    "libimagentrytag",
    "libimagentryview",
    "libimagerror",
    "libimaginteraction",
    "libimagmail",
    "libimagnotes",
    "libimagref",
    "libimagrt",
    "libimagstore",
    "libimagtimeui",
    "libimagtodo",
    "libimagutil",
]
