[workspace]
members = [
    ".imag-documentation",
    "bin",
    "imag-link",
    "imag-notes",
    "imag-ref",
    "imag-store",
    "imag-tag",
    "imag-view",
    "libimagannotation",
    "libimagentryedit",
    "libimagentryfilter",
    "libimagentrylink",
    "libimagentrylist",
    "libimagentrymarkdown",
    "libimagentrytag",
    "libimagentryview",
    "libimagerror",
    "libimaginteraction",
    "libimagnotes",
    "libimagref",
    "libimagrt",
    "libimagruby",
    "libimagstore",
    "libimagstorestdhook",
    "libimagtimeui",
    "libimagutil",
]
