[package]
name = "imag-habit"
version = "0.10.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-habit command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://imag-pim.org/doc/"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
chrono = "0.4.7"
log = "0.4.6"
toml = "0.5.1"
toml-query = "0.9.2"
kairos = "0.3.0"
prettytable-rs = "0.8.0"
failure = "0.1.5"

libimagerror       = { version = "0.10.0", path = "../../../lib/core/libimagerror" }
libimagstore       = { version = "0.10.0", path = "../../../lib/core/libimagstore" }
libimagrt          = { version = "0.10.0", path = "../../../lib/core/libimagrt" }
libimagentryedit   = { version = "0.10.0", path = "../../../lib/entry/libimagentryedit" }
libimaginteraction = { version = "0.10.0", path = "../../../lib/etc/libimaginteraction" }
libimagutil        = { version = "0.10.0", path = "../../../lib/etc/libimagutil" }
libimagtimeui      = { version = "0.10.0", path = "../../../lib/etc/libimagtimeui" }
libimaghabit       = { version = "0.10.0", path = "../../../lib/domain/libimaghabit" }

[dependencies.clap]
version = "2.33.0"
default-features = false
features = ["color", "suggestions", "wrap_help"]

[lib]
name = "libimaghabitfrontend"
path = "src/lib.rs"

[[bin]]
name = "imag-habit"
path = "src/bin.rs"
