[package]
name = "imag-log"
version = "0.10.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-log command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://imag-pim.org/doc/"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
log = "0.4.6"
toml = "0.5.1"
toml-query = "0.9.2"
is-match = "0.1.0"
itertools = "0.8.0"
failure = "0.1.5"
textwrap = "0.11.0"

libimagstore = { version = "0.10.0", path = "../../../lib/core/libimagstore" }
libimagrt    = { version = "0.10.0", path = "../../../lib/core/libimagrt" }
libimagerror = { version = "0.10.0", path = "../../../lib/core/libimagerror" }
libimagdiary = { version = "0.10.0", path = "../../../lib/domain/libimagdiary" }
libimaglog   = { version = "0.10.0", path = "../../../lib/domain/libimaglog" }

[dependencies.clap]
version = "2.33.0"
default-features = false
features = ["color", "suggestions", "wrap_help"]

[lib]
name = "libimaglogfrontend"
path = "src/lib.rs"

[[bin]]
name = "imag-log"
path = "src/bin.rs"
