[package]
name = "imag-diagnostics"
version = "0.10.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-diagnostics command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://imag-pim.org/doc/"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
log  = "0.4.6"
toml = "0.5.1"
toml-query = "0.9.2"
indicatif  = "0.12.0"
failure    = "0.1.5"
resiter    = "0.3.0"

libimagstore     = { version = "0.10.0", path = "../../../lib/core/libimagstore" }
libimagrt        = { version = "0.10.0", path = "../../../lib/core/libimagrt" }
libimagerror     = { version = "0.10.0", path = "../../../lib/core/libimagerror" }
libimagentrylink = { version = "0.10.0", path = "../../../lib/entry/libimagentrylink" }

[dependencies.clap]
version = "2.33.0"
default-features = false
features = ["suggestions", "color", "wrap_help"]

[lib]
name = "libimagdiagnosticscmd"
path = "src/lib.rs"

[[bin]]
name = "imag-diagnostics"
path = "src/bin.rs"
