[package]
name = "imag-notes"
version = "0.10.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-notes command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://imag-pim.org/doc/"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
log = "0.4.6"
itertools = "0.8.0"
failure = "0.1.5"

libimagrt        = { version = "0.10.0", path = "../../../lib/core/libimagrt" }
libimagerror     = { version = "0.10.0", path = "../../../lib/core/libimagerror" }
libimagnotes     = { version = "0.10.0", path = "../../../lib/domain/libimagnotes" }
libimagentryedit = { version = "0.10.0", path = "../../../lib/entry/libimagentryedit" }
libimagutil      = { version = "0.10.0", path = "../../../lib/etc/libimagutil" }
libimagstore     = { version = "0.10.0", path = "../../../lib/core/libimagstore" }

[dependencies.clap]
version = "2.33.0"
default-features = false
features = ["color", "suggestions", "wrap_help"]

[lib]
name = "libimagnotesfrontend"
path = "src/lib.rs"

[[bin]]
name = "imag-notes"
path = "src/bin.rs"
