[package]
authors = ["Matthias Beyer <mail@beyermatthias.de>"]
name = "imag-todo"
version = "0.10.0"

description = "Part of the imag core distribution: imag-todo command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://imag-pim.org/doc/"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
log = "0.4.6"
toml = "0.5.1"
toml-query = "0.9.2"
is-match = "0.1.0"
failure  = "0.1.5"
chrono = "0.4"
filters = "0.3"
kairos = "0.3"
resiter = "0.4.0"

libimagrt        = { version = "0.10.0", path = "../../../lib/core/libimagrt" }
libimagstore        = { version = "0.10.0", path = "../../../lib/core/libimagstore" }
libimagerror     = { version = "0.10.0", path = "../../../lib/core/libimagerror" }
libimagentryedit = { version = "0.10.0", path = "../../../lib/entry/libimagentryedit" }
libimagtodo      = { version = "0.10.0", path = "../../../lib/domain/libimagtodo" }
libimagutil      = { version = "0.10.0", path = "../../../lib/etc/libimagutil" }
libimagentryview      = { version = "0.10.0", path = "../../../lib/entry/libimagentryview" }

[dependencies.clap]
version = "2.33.0"
default-features = false
features = ["color", "suggestions", "wrap_help"]

[dependencies.task-hookrs]
version = "0.7.0"
optional = true

[dependencies.uuid]
version = "0.7.4"
features = ["v4"]
optional = true

[dependencies.libimagentrytag]
version = "0.10.0"
path = "../../../lib/entry/libimagentrytag"
optional = true

[dependencies.libimagentrylink]
version = "0.10.0"
path = "../../../lib/entry/libimagentrylink"
optional = true


[lib]
name = "libimagtodofrontend"
path = "src/lib.rs"

[[bin]]
name = "imag-todo"
path = "src/bin.rs"

[features]
default = []
import-taskwarrior = [ "task-hookrs", "uuid", "libimagentrytag", "libimagentrylink" ]

