[package]
name = "imag-calendar"
version = "0.10.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]
edition = "2018"

description = "Part of the imag core distribution: imag-calendar command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://imag-pim.org/doc/"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
log        = "0.4"
failure    = "0.1"
walkdir    = "2.2.8"

libimagrt          = { version = "0.10.0", path = "../../../lib/core/libimagrt" }
libimagstore       = { version = "0.10.0", path = "../../../lib/core/libimagstore" }
libimagerror       = { version = "0.10.0", path = "../../../lib/core/libimagerror" }
libimagutil        = { version = "0.10.0", path = "../../../lib/etc/libimagutil" }
libimagentryref    = { version = "0.10.0", path = "../../../lib/entry/libimagentryref" }
libimagentryedit   = { version = "0.10.0", path = "../../../lib/entry/libimagentryedit" }
libimaginteraction = { version = "0.10.0", path = "../../../lib/etc/libimaginteraction" }
libimagcalendar    = { version = "0.10.0", path = "../../../lib/domain/libimagcalendar" }

[dependencies.clap]
version = "2.33.0"
default-features = false
features = ["color", "suggestions", "wrap_help"]

[dependencies.toml-query]
version          = "0.9.2"
default-features = false
features         = ["typed"]

