[package]
name = "imag-wiki"
version = "0.10.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-wiki command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
clap = "2.33.0"
log = "0.4.6"
toml = "0.5.1"
toml-query = "0.9.2"
is-match = "0.1.0"
regex = "1.1.7"
filters = "0.3.0"
failure = "0.1.5"

libimagentryedit     = { version = "0.10.0", path = "../../../lib/entry/libimagentryedit" }
libimagentrylink     = { version = "0.10.0", path = "../../../lib/entry/libimagentrylink" }
libimagentrymarkdown = { version = "0.10.0", path = "../../../lib/entry/libimagentrymarkdown" }
libimagerror         = { version = "0.10.0", path = "../../../lib/core/libimagerror" }
libimagrt            = { version = "0.10.0", path = "../../../lib/core/libimagrt" }
libimagstore         = { version = "0.10.0", path = "../../../lib/core/libimagstore" }
libimagwiki          = { version = "0.10.0", path = "../../../lib/domain/libimagwiki" }
libimagutil          = { version = "0.10.0", path = "../../../lib/etc/libimagutil" }

[lib]
name = "libimagwikifrontend"
path = "src/lib.rs"

[[bin]]
name = "imag-wiki"
path = "src/bin.rs"
