[package]
name = "imag-contact"
version = "0.10.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-contact command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://imag-pim.org/doc/"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
log = "0.4.6"
toml = "0.5.1"
vobject    = "0.7.0"
handlebars = "2"
walkdir = "2.2.8"
uuid = { version = "0.7.4", features = ["v4"] }
serde_json = "1.0.39"
failure = "0.1.5"

libimagrt          = { version = "0.10.0", path = "../../../lib/core/libimagrt" }
libimagstore       = { version = "0.10.0", path = "../../../lib/core/libimagstore" }
libimagerror       = { version = "0.10.0", path = "../../../lib/core/libimagerror" }
libimagutil        = { version = "0.10.0", path = "../../../lib/etc/libimagutil" }
libimagentryref    = { version = "0.10.0", path = "../../../lib/entry/libimagentryref" }
libimagentryedit   = { version = "0.10.0", path = "../../../lib/entry/libimagentryedit" }
libimaginteraction = { version = "0.10.0", path = "../../../lib/etc/libimaginteraction" }
libimagcontact     = { version = "0.10.0", path = "../../../lib/domain/libimagcontact" }

[dependencies.clap]
version = "2.33.0"
default-features = false
features = ["color", "suggestions", "wrap_help"]

[dependencies.toml-query]
version          = "0.9.2"
default-features = false
features         = ["typed"]

[lib]
name = "libimagcontactfrontend"
path = "src/lib.rs"

[[bin]]
name = "imag-contact"
path = "src/bin.rs"
