#!/usr/bin/env bash

since="$1"

if [[ -z "$since" ]]; then
    echo "Usage: $0 [since]"
    exit 1
fi

export GIT_PAGER=

do_log() {
    git log "$since"..HEAD --first-parent --oneline "$@"
}

echo " ### Major changes"
echo ""
    do_log \
    --merges \
    --format="* (%h) %s"
echo ""
echo ""

echo " ### Fixes"
echo ""
    do_log \
    --grep Fix \
    --format="* (%h) %s"
echo ""
echo ""


echo " ### Other "
echo ""
    do_log \
    --no-merges \
    --grep Fix \
    --invert-grep \
    --format="* (%h) %s"
echo ""
echo ""

echo "Thanks to all contributors:"
# do not thank myself...
do_log --format="* %an" | sort -u | grep -v "Matthias Beyer"

