require 'thermite/tasks'

Thermite::Tasks.new(cargo_project_path: "..", cargo_workspace_member: "libimagruby", ruby_project_path: ".")

task default: %w(thermite:build)

desc 'Run Rust & Ruby testsuites'
task test: ['thermite:build', 'thermite:test'] do
  [ "test_methods_present"
  , "test_store_crud"
  ].each do |name|
    ruby File.join(File.dirname(__FILE__), 'tests', "#{name}.rb")
  end
end
